sm_project/urls.py
from django.apps import apps
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("lang/", views.lang, name="lang"),
    path("i18n/", include("django.conf.urls.i18n")),
]

if apps.is_installed("survey"):
    urlpatterns.append(path("survey/", include("survey.urls")))

survey/urls.py
from django.urls import path
from . import views

# import survey

app_name = "survey"

urlpatterns = [
    path("", views.home, name="home"),
    path("list/", views.list, name="list"),
    path("choose/", views.choose, name="choose"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:survey_id>/vote/", views.vote, name="vote"),
    path("results/<int:pk>/", views.ResultsView.as_view(), name="results"),
    path("completed/", views.completed, name="completed"),
    path("<int:survey_id>/stats/", views.stats, name="stats"),
    path(
        "<int:survey_id>/stats/<int:reference_id>/", views.stats, name="reference_stats"
    ),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as users_views

urlpatterns = [
    path('register/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

survey/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

# Create your models here.
class Survey(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=_("name"))

    class Meta:
        permissions = (
            (
                "view_stats",
                _("Can see statistics on surveys"),
            ),
        )
        verbose_name = _("survey")
        verbose_name_plural = _("surveys")

    def __str__(self):
        return self.name


class Question(models.Model):
    text = models.CharField(max_length=64, unique=True, verbose_name=_("text"))
    multiple_choice = models.BooleanField(
        default=False, null=False, verbose_name=_("multiple choice")
    )
    respondents_particulars = models.BooleanField(
        default=False, null=False, verbose_name=_("respondents particulars")
    )

    class Meta:
        verbose_name = _("question")
        verbose_name_plural = _("questions")

    def __str__(self):
        return self.text


class SurveyQuestion(models.Model):
    survey = models.ForeignKey(
        Survey, on_delete=models.CASCADE, verbose_name=_("survey")
    )
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name=_("question")
    )

    class Meta:
        verbose_name = _("relation of survey to question")
        verbose_name_plural = _("relation of surveys to questions")

    def __str__(self):
        return f"{self.survey}: {self.question}"


class Answer(models.Model):
    text = models.CharField(max_length=16, unique=True, verbose_name=_("text"))

    class Meta:
        verbose_name = _("answer")
        verbose_name_plural = _("answers")

    def __str__(self):
        return self.text


class QuestionAnswer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name=_("question")
    )
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, verbose_name=_("answer")
    )

    class Meta:
        verbose_name = _("relation of question to answer")
        verbose_name_plural = _("relations of questions to answers")

    def __str__(self):
        return f"{self.question}: {self.answer}"


class Response(models.Model):
    bill_no = models.TextField(max_length=8, verbose_name=_("bill number"))
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("user")
    )
    survey = models.ForeignKey(
        Survey, on_delete=models.CASCADE, verbose_name=_("survey")
    )

    class Meta:
        unique_together = (
            "bill_no",
            "survey",
        )
        verbose_name = _("response")
        verbose_name_plural = _("responses")

    def __str__(self):
        username = self.user
        if not username:
            username = _("unlogged user")

        return f"[{self.bill_no}] {username}: {self.survey}"


class ResponseAnswer(models.Model):
    response = models.ForeignKey(
        Response, on_delete=models.CASCADE, verbose_name=_("response")
    )
    question_answer = models.ForeignKey(
        QuestionAnswer,
        on_delete=models.CASCADE,
        verbose_name=_("relation of question to answer"),
    )

    class Meta:
        verbose_name = _("answer of survey response")
        verbose_name_plural = _("answers of survey responses")

    def __str__(self):
        return f"[{self.response.bill_no}] {self.question_answer.question} ({self.question_answer.answer})"

survey/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.db.utils import IntegrityError
from django.views import generic
from django.utils.translation import ugettext as _

from .models import (
    Question,
    QuestionAnswer,
    Response,
    ResponseAnswer,
    Survey,
    SurveyQuestion,
)

import re
from dataclasses import dataclass


def home(request):
    return render(request, "survey/home.html")


@login_required
@permission_required("survey.view", raise_exception=True)
def list(request):
    context = {
        "survey_list_id_asc": Survey.objects.order_by("id").all(),
    }
    return render(request, "survey/list.html", context)


def choose(request):
    context = {
        "survey_list_name_asc": Survey.objects.order_by("name").all(),
    }
    return render(request, "survey/choose.html", context)


class DetailView(generic.DetailView):
    model = Survey
    template_name = "survey/detail.html"


def vote(request, survey_id):
    if request.method != "POST":
        return render(request, "survey/vote.html")

    survey = get_object_or_404(Survey, pk=survey_id)

    user = None
    if request.user.is_authenticated:
        user = request.user

    try:
        bill_no_upper = request.POST["bill-no"].upper()

        if re.match(r"([A-Z0-9]){8}", bill_no_upper):
            response = Response(bill_no=bill_no_upper, user=user, survey=survey)
            response.save()
        else:
            return render(
                request,
                "survey/detail.html",
                {
                    "post_data": request.POST.lists(),
                    "survey": survey,
                    "error_message": _("Incorrect bill number format"),
                },
            )

    except IntegrityError:
        return render(
            request,
            "survey/detail.html",
            {
                "post_data": request.POST.lists(),
                "survey": survey,
                "error_message": _(
                    "You have already completed this survey using the bill number provided"
                ),
            },
        )

    survey_questions = survey.surveyquestion_set.all()
    for survey_question in survey_questions:
        question_id = survey_question.question.id

        field_name = f"question{question_id}"
        question_answers = request.POST.getlist(field_name)

        if not question_answers:
            response.delete()  # change if you have an idea

            return render(
                request,
                "survey/detail.html",
                {
                    "post_data": request.POST.lists(),
                    "survey": survey,
                    "error_message": _(
                        "You did not choose an answer to one of the questions"
                    ),
                },
            )

        for answer in question_answers:
            selected_question_answer = survey_question.question.questionanswer_set.get(
                answer_id=answer,
                question_id=question_id,
            )

            response_answer = ResponseAnswer(
                response=response,
                question_answer=selected_question_answer,
            )
            response_answer.save()

    return HttpResponseRedirect(reverse("survey:results", args=(response.id,)))


class ResultsView(generic.DetailView):
    model = Response
    template_name = "survey/results.html"


@login_required
def completed(request):
    context = {"user_responses": Response.objects.filter(user=request.user)}
    return render(request, "survey/completed.html", context)


@login_required
@permission_required("survey.view_stats", raise_exception=True)
def stats(request, survey_id, reference_id=None):
    survey = get_object_or_404(Survey, pk=survey_id)

    # handle url with reference QuestionAnswer id
    reference_qa = None

    if reference_id:
        reference_qa = get_object_or_404(
            QuestionAnswer, pk=reference_id, question__respondents_particulars=True
        )

    # get list of QuestionAnswer objects with respondents particulars questions for the survey
    respondents_particulars_questions = Question.objects.filter(
        respondents_particulars=True
    )
    survey_sqs = SurveyQuestion.objects.filter(survey=survey)

    rp_question_answers = []

    for survey_question in survey_sqs:
        if survey_question.question in respondents_particulars_questions:
            for question_answer in survey_question.question.questionanswer_set.all():
                rp_question_answers.append(question_answer)

    # check if reference_qa is valid for the survey
    if reference_qa and not reference_qa in rp_question_answers:
        reference_qa = None

    # create dataclass to keep stats in simple object
    @dataclass
    class QuestionStats:
        question_answer: QuestionAnswer
        reference_qa: QuestionAnswer = None
        count: int = 0

    # create list of QuestionStats objects with every possible combination for the survey
    stats_list = []

    for response in survey.response_set.all():
        response_answers = response.responseanswer_set.all()

        for response_answer in response_answers:
            filtered_stats_list = [
                x
                for x in stats_list
                if x.question_answer == response_answer.question_answer
            ]

            if not filtered_stats_list:
                filtered_stats_list.append(
                    QuestionStats(question_answer=response_answer.question_answer)
                )

                for question_answer in rp_question_answers:
                    if (
                        response_answer.question_answer.question
                        != question_answer.question
                    ):
                        filtered_stats_list.append(
                            QuestionStats(
                                question_answer=response_answer.question_answer,
                                reference_qa=question_answer,
                            )
                        )

                stats_list.extend(filtered_stats_list)

            for question_stats in filtered_stats_list:
                if question_stats.reference_qa is None:
                    question_stats.count += 1
                elif question_stats.reference_qa in rp_question_answers:
                    for response_answer2 in response_answers:
                        if (
                            response_answer2.question_answer
                            == question_stats.reference_qa
                        ):
                            question_stats.count += 1

    stats_list = [x for x in stats_list if x.count > 0]

    titles = []
    labels_set = []
    data_set = []

    survey_question_set = survey.surveyquestion_set.all()

    for survey_question in survey_question_set:
        labels = []
        data = []

        for question_stats in stats_list:
            if survey_question.question == question_stats.question_answer.question:
                if question_stats.reference_qa == reference_qa:
                    labels.append(question_stats.question_answer.answer.text)
                    data.append(question_stats.count)

        if labels and data:
            titles.append(survey_question.question)
            labels_set.append(labels)
            data_set.append(data)

    zipped_data = zip(titles, labels_set, data_set)

    max_len = 0
    if data_set:
        max_len = len(max(data_set, key=len))

    context = {
        "survey": survey,
        "rp_question_answers": rp_question_answers,
        "reference_id": reference_id,
        "max_len": max_len,
        "zipped_data": zipped_data,
    }

    return render(request, "survey/stats.html", context)

survey/templates/survey/choose.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Select survey" %}</h1>

    <p>
        {% translate "Please select the survey you would like to complete." %}
        {% translate "Have your receipt number ready." %}
    </p>

    {% if survey_list_name_asc %}
    <ul>
    {% for survey in survey_list_name_asc %}
        <li><a href="{% url 'survey:detail' survey.id %}">{{ survey }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>{% translate "No surveys available." %}</p>
    {% endif %}
{% endblock content %}

survey/templates/survey/completed.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Completed surveys" %}</h1>

    <p>
        {% translate "Below is a list of the surveys you have completed." %}
        {% translate "In order to go to the preview of selected answers, press the proper link." %}
    </p>

    {% if user_responses %}
        <ol>
        {% for response in user_responses %}
            <li><p>
                {% translate "bill number"|capfirst %}: {{ response.bill_no }}<br>
                {% translate "survey"|capfirst %}: {{ response.survey }}<br>
                <a href="{% url 'survey:results' response.id %}">{% translate "Show answers" %}</a>
            </p></li>
        {% endfor %}
        </ol> 
    {% else %}
        <p>{% translate "You did not complete any survey." %}</p>
    {% endif %}
    
{% endblock content %}

survey/templates/survey/detail.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}
{% load custom_template_tags %}

{% block content %}
    <h1>{% translate "Completing a survey" %}</h1>

    {% if perms.survey.view_stats %}
    <p><a href="{% url 'survey:stats' survey.id %}">{% translate "Go to statistics" %}</a></p>
    {% endif %}

    <form action="{% url 'survey:vote' survey.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><p class="lead"><b>{% translate "Title" %}:</b> {{ survey }}</p></legend>

            {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
            {% endif %}

            <label for="bill-no">{% translate "bill number"|capfirst %} ({% translate "numbers and letters" %}, 8 {% translate "characters" %}):</label>
            <input type="text" id="bill-no" name="bill-no" maxlength="8">
            
            <br><br>

            <ol>
                {% for survey_question in survey.surveyquestion_set.all %}
                <li>
                <div class="container"> 
                    <p>{{ survey_question.question }}</p>
                    {% for question_answer in survey_question.question.questionanswer_set.all %}
                        {% if survey_question.question.multiple_choice %}
                            {% setvar "checkbox" as type %}
                        {% else %}
                            {% setvar "radio" as type %}
                        {% endif %}
                    
                    <input type="{{ type }}" name="question{{ survey_question.question.id }}" id="q{{ survey_question.question.id }}-a{{ forloop.counter }}" value="{{ question_answer.answer.id }}">
                    <label for="q{{ survey_question.question.id }}-a{{ forloop.counter }}">{{ question_answer.answer }}</label><br>
                    {% endfor %}
                {% endfor %}
                </div>
                </li>
            </ol>
            
        </fieldset>
        <button type="submit" class="btn btn-primary">{% translate "Send" %}</button>
    </form>

    {% if post_data %}
    <script>
        $(document).ready(function() {
            let dict = {};
            let values;

            {% for item in post_data %}
            values = [];
                {% for value in item.1 %}
                values.push("{{ value }}");
                {% endfor %}
            dict["{{ item.0 }}"] = values;
            {% endfor %}

            restoreFormData(dict);
        });
    </script>
    {% endif %}
{% endblock content %}

survey/templates/survey/home.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Customer satisfaction survey" %}</h1>

    <p>
        {% translate "In this tab you can rate your experience after visiting our restaurant." %}<br>
        {% translate "Surveys are available without registration or logging in." %}
        {% translate "People with an account on our website have access to the history of the surveys they have completed." %}
    </p>
{% endblock content %}

survey/templates/survey/list.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "List of surveys" %}</h1>

    <p>{% translate "Click on a survey title to display a list of questions with answers." %}</p>

    {% for survey in survey_list_id_asc %}
    <details>
        <summary>{{ survey }}</summary>

        {% if perms.survey.view_stats %}
        <p><a href="{% url 'survey:stats' survey.id %}">{% translate "Go to statistics" %}</a></p>
        {% endif %}

        <ol>
            {% for survey_question in survey.surveyquestion_set.all %}
            <li>{{ survey_question.question }}</li>
            <ul>
                {% for question_answer in survey_question.question.questionanswer_set.all %}
                <li>{{ question_answer.answer }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </ol>
    </details>        
    {% empty %}
    <p>{% translate "No surveys available." %}</p>
    {% endfor %}

    <script>
    document.addEventListener("DOMContentLoaded", function(){
        var detailsList = document.getElementsByTagName('details');

        for (const detailsElement of detailsList) {
            detailsElement.addEventListener("toggle", function(){
                var summariesList = detailsElement.getElementsByTagName('summary');
                for (const summaryElement of summariesList) {
                    if (detailsElement.open) {
                        summaryElement.style = "font-weight:bold;"
                    } else {
                        summaryElement.style = "font-weight:normal;"
                    }
                }
            }); 
        }
    });
    </script>
    
{% endblock content %}

survey/templates/survey/results.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Survey results" %}</h1>
    {% if user == response.user %}
    <p class="lead">{% translate "Selected answers" %}:</p>
    <div class="container">
        <ul>
            {% for survey_question in response.survey.surveyquestion_set.all %}
                <li>
                    <b>{{ survey_question.question }}</b>
                    <ul>
                    {% for response_answer in response.responseanswer_set.all %}
                        {% if survey_question.question == response_answer.question_answer.question %}
                        <li>{{ response_answer.question_answer.answer }}</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <p>{% translate "The survey was filled in correctly." %}</p>
    {% endif %}

{% endblock content %}

survey/templates/survey/stats.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}
{% load custom_template_tags %}

{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>

    <!-- Import D3 Scale Chromatic via CDN -->
    <script src="https://d3js.org/d3-color.v1.min.js"></script>
    <script src="https://d3js.org/d3-interpolate.v1.min.js"></script>
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

    <h1>{% translate "Survey statistics" %}</h1>
    <p class="lead"><b>{% translate "Title" %}:</b> {{ survey.name }}</p>
    <div class="container" id="chart-container" style="max-width: 600px; max-height: 600px;">

        <div class="select-container">
            <label for="reference">{% translate "Data for the group" %}:</label>
            <select class="custom-select" name="reference" id="reference">
                <option value="0">{% translate "none" %}</option>
                {% for qa in rp_question_answers %}
                <option value="{{ qa.id }}">{{ qa.question }}: {{ qa.answer }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="select-container">
            <label for="chart-type">{% translate "Type of charts" %}:</label>
            <select class="custom-select" name="chart-type" id="chart-type">
                <option value="pie" selected>{% translate "Pie" %}</option>
                <option value="doughnut">{% translate "Doughnut" %}</option>
                <option value="bar">{% translate "Bar" %}</option>        
            </select>
        </div>

        <script>
            $("#reference").change(function() {
                let referenceValue = $(this).val();
                console.log(referenceValue);

                if (referenceValue == 0){
                    window.location = "{% url 'survey:stats' survey_id=survey.id %}";
                } else {
                    window.location = "{% url 'survey:reference_stats' survey_id=survey.id reference_id=0 %}".replace(/0/, referenceValue);
                }
                           
            });

            {% if reference_id %}
            $("#reference").val({{ reference_id }});
            {% endif %}
        </script>

    {% for title, labels, data in zipped_data %}
        {% if forloop.first %}
        <!-- Charts config -->
        <script>
            const borderWidth = 1;
            const colorScale = d3.interpolateWarm;
            const colorRangeInfo = {
                colorStart: 0,
                colorEnd: 1,
                useEndAsStart: false,
            }; 

            var rgb_colors = interpolateColors({{ max_len }}, colorScale, colorRangeInfo);
            var rgba_colors = [];

            for (let color of rgb_colors) {
                new_color = color.replace(/rgb/i, "rgba");
                new_color = new_color.replace(/\)/i,',0.2)');

                rgba_colors.push(new_color);
            }

            var ctx = [];
            var data = [];
            var options = [];
            var charts = [];

            function setSelectedChartType() {
                let chartType = $("#chart-type").val();

                for (let i = 0; i < ctx.length; i++) {
                    if (i in charts) {
                        if(charts[i].config.type === chartType) {
                            continue;                            
                        }
                        charts[i].destroy();
                    }  

                    switch(chartType) {
                        case 'bar':
                            options[i].plugins.legend.display = false;
                            options[i].scales.y.display = true;
                            options[i].scales.y.grid.display = true;

                            if('x' in options[i].scales) {
                                options[i].scales.x.display = true;
                                options[i].scales.x.grid.display = true;
                            }
                            
                            break;
                        case 'pie':
                        case 'doughnut':
                            options[i].plugins.legend.display = true;
                            options[i].scales.y.display = false;
                            options[i].scales.y.grid.display = false;

                            if('x' in options[i].scales) {
                                options[i].scales.x.display = false;
                                options[i].scales.x.grid.display = false;
                            }

                            break;
                    }             

                    charts[i] = new Chart(ctx[i], {
                        type: chartType,
                        data: data[i],
                        options: options[i]
                    });
                }
            }

            $("#chart-type").change(setSelectedChartType);
        </script>
        {% endif %}
    
    <canvas id="chart{{ forloop.counter0 }}-canvas"></canvas>
    <a download='chart' href="#" class="btn btn-dark btn-sm disabled" id="chart{{ forloop.counter0 }}-url">{% translate "Download chart in PNG" %}</a>
    
    <script>
        $(document).ready(function() {
            ctx[{{ forloop.counter0 }}] = $("#chart{{ forloop.counter0 }}-canvas").get(0).getContext("2d");

            data[{{ forloop.counter0 }}] = {
                labels: {{ labels|safe }},
                datasets: [
                    {
                        data: {{ data|safe }},
                        borderColor: rgb_colors,
                        borderWidth: borderWidth,
                        backgroundColor: rgba_colors
                    }
                ]
            };
            options[{{ forloop.counter0 }}] = {
                responsive: true,
                plugins: {
                    title: {
                        display: true,
                        text: '{{ title|safe }}'
                    },
                    legend: {
                        display: true,
                        position: 'top',
                    }
                },
                scales: {
                    y: {
                        display: false,
                        min: 0,
                        ticks: {                            
                            stepSize: 1
                        },
                        grid: {
                            display: false
                        }
                    }
                },
                animation: {
                    onComplete: function() {
                        var base64 = this.toBase64Image();
                        $("#chart{{ forloop.counter0 }}-url").attr("href", base64).removeClass("disabled");
                    }
                }  
            };

            {% if forloop.last %}
            setSelectedChartType();
            {% endif %}
        });
                    
    </script>
    {% empty %}
    <div class="alert alert-dark" role="alert">{% translate "No data to be presented in the charts." %}</div>
    {% endfor %}
    </div>
{% endblock content %}

survey/templates/survey/survey_menu.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'survey:home' %}">{% translate "Customer satisfaction survey" %}</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'survey:choose' %}">{% translate "Select survey" %}</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'survey:completed' %}">{% translate "Completed surveys" %}</a>
    </li>

        {% if perms.survey.view %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'survey:list' %}">{% translate "List of surveys" %}</a>
        </li>
        {% endif %}
    {% endif %}
{% endblock menu %}

survey/templates/survey/vote.html
{% extends "survey/survey_menu.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Completing a survey" %}</h1>

    <p>{% translate "To vote in a survey, you must go to the corresponding subpage." %}</p>
    <a href="{% url 'survey:choose' %}">{% translate "Select survey" %}</a>
{% endblock content %}